name: Pull_Request

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out âœŠ
        uses: actions/checkout@v3

      - name: Ballerina Test ðŸ›¡
        uses: ballerina-platform/ballerina-action/@2201.7.1
        with:
          args: test --test-report --code-coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
