name: Pull_Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out âœŠ
        uses: actions/checkout@v3

      - name: Ballerina Test ğŸ›¡
        uses: ballerina-platform/ballerina-action/@2201.7.1
        with:
          args: test --test-report --code-coverage

      - name: Check Failed ğŸ‘€
        if: fromJson(./target/report/test_results.json).failed > 0
        run: echo "Test Failed â"

      - name: Check Success ğŸ‘€
        if: fromJson(./target/report/test_results.json).failed <= 0
        run: echo "Test Success âœ…"
